pipeline:
  build:
    image: rocker/tidyverse
    commands:
      - echo "Start"
      - Rscript -e "install.packages('kableExtra'); rmarkdown::render('ex_kableExtra.Rmd', output_dir='../docs/')"
      - echo "End"
